sudo: false
language: ruby
rvm:
  - 2.5.1
  - 2.4.4
  - 2.3.7
  - 2.2.10
  - 2.1.10
before_install:
  - gem update --system
  - gem install bundler
script: 'bundle exec rspec'
cache: bundler
matrix:
  fast_finish: true
